Ajout de la commande redirect
abyo/layton-bot pull request #25
Opened 2022-03-31 19:12 UTC by TsWin

## Ajouts
- Commande `redirect` dans la catégorie moderation

## Actions
- Closes #20 

## Commentaires
C'est ma première slash command donc n'hésitez pas à corriger. 😄

2022-03-31 19:26 UTC, Smaug6739 commented
Pour améliorer la commande tu pourrais mieux cibler les channels de type texte avec la key `channelTypes` sur ton option et mettre l'option `required` sur `true`. De cette facon si un utilisateur fais une erreur en tapant la commande (en oublient un paramètre ou en mettant un channel de type voice)  ca fera pas cracher le bot en permettant d'enlever 2 conditions et cela améliore l'expérience utilisateur.
Sinon un truc que on peut ajouter c'est la prise en charge des images et fichiers. Certains membres envoient leur code ou autre en image ou en fichier donc ca peut être pratique.

2022-03-31 19:33 UTC, TsWin commented
@Smaug6739 D'accord merci du conseil, j'y penserais la prochaine fois.
Je regarde pour ajouter la prise en charge des images et fichiers 👍

2022-03-31 20:00 UTC, Smaug6739 requested changes

2022-03-31 20:06 UTC, TsWin commented on commands/moderation/redirect.js
> +      channelType: "text",
Désolé, je n'arrivais pas à trouver sur la documentation, merci 😓

2022-03-31 20:12 UTC, Smaug6739 requested changes

2022-03-31 20:12 UTC, Smaug6739 commented on commands/moderation/redirect.js
> +    const message = await channel.messages.fetch(messageId);
La variable `channel` correspond à l'option de la commande. Donc si on fetch les messages dans le channel dans le quel on souhaite rediriger le message ça va pas aller.
Exemple si on veut rediriger un message d'un channel A vers un channel B on va fetch le message dans le channel A et l'envoyer dans B. La on fetch dans B pour envoyer dans B.

2022-03-31 20:14 UTC, TsWin commented on commands/moderation/redirect.js
> +    const message = await channel.messages.fetch(messageId);
🤦

2022-03-31 20:26 UTC, Smaug6739 commented
On devrait pouvoir automatiquement donner le role à la personne pour voir le salon si elle ne l'a pas déjà. Je n'ai pas les permissions de voir comment ont été paramètrés les rôles sur le serveur mais j'imagine que on peut prendre les dérogation du salon, enlever le rôle everyone et récupérer les rôles (sans pouvoir de modération) qui ont accès à ce channel. Il suffira ensuite de l'attribuer au membre si il ne l'a pas.
Autre méthode : Lister tous les channels et rôles associés dans un JSON. C'est sûrement plus simple mais ça oblige une update à chaque changement sur le serveur

2022-04-01 13:04 UTC, TsWin commented
J'y ai pensé aussi aux deux solutions, cependant je n'ai pas accès à la configuration des salons ni-même des rôles. Je ne saurais te dire. Peut être @abyo peut nous éclaircir.

2022-04-01 14:38 UTC, abyo commented
Pas besoin de faire compliquer, map les id's des rôles aux salons. De ce fait, lorsque le nom du salon est spécifié, le rôle sera aussi automatiquement récupéré.

2022-04-02 10:35 UTC, abyo approved these changes

2022-04-02 10:36 UTC, merged